
// this var will be injected via index.html and server-side include
const injectedEnv = window["INJECTED_ENVIRONMENT"];
let seedEnv: Environment;

if (!injectedEnv) {
  console.warn("Angular PROJ Template DEFAULT DEVELOPMENT ENV");
  seedEnv = {
    realm: "TH-Bingen",
    token:
      "bearer eyJhbGciOiJSUzI1NiIsImprdSI6Imh0dHBzOi8vdWFhLnN5c3RlbS5jZi5ob2IubG9jYWwvdG9rZW5fa2V5cyIsImtpZCI6ImtleS0xIiwidHlwIjoiSldUIn0.eyJqdGkiOiJhNDFhZjE1NzEwNDk0NjkzOWMzMWI2YjNjODFjZjI1ZiIsInN1YiI6ImFjNTcxOGQ4LThlZjEtNDc1ZS1hZWYzLTUyNjk5YzlmNjAwZSIsInNjb3BlIjpbImNsb3VkX2NvbnRyb2xsZXJfc2VydmljZV9wZXJtaXNzaW9ucy5yZWFkIiwib3BlbmlkIl0sImNsaWVudF9pZCI6Im9zYi1sb2ctbWV0cmljLXRlc3Quc3lzdGVtLmNmLmhvYi5sb2NhbCIsImNpZCI6Im9zYi1sb2ctbWV0cmljLXRlc3Quc3lzdGVtLmNmLmhvYi5sb2NhbCIsImF6cCI6Im9zYi1sb2ctbWV0cmljLXRlc3Quc3lzdGVtLmNmLmhvYi5sb2NhbCIsImdyYW50X3R5cGUiOiJhdXRob3JpemF0aW9uX2NvZGUiLCJ1c2VyX2lkIjoiYWM1NzE4ZDgtOGVmMS00NzVlLWFlZjMtNTI2OTljOWY2MDBlIiwib3JpZ2luIjoiRXZvaWxhU1NPIiwidXNlcl9uYW1lIjoibW1haGxlciIsImVtYWlsIjoibW1haGxlckBldm9pbGEuZGUiLCJhdXRoX3RpbWUiOjE2MDU4NjIzODgsInJldl9zaWciOiI0ZDc3MzdhZiIsImlhdCI6MTYwNTg2MjM4OSwiZXhwIjoxNjA1OTA1NTg5LCJpc3MiOiJodHRwczovL3VhYS5zeXN0ZW0uY2YuaG9iLmxvY2FsL29hdXRoL3Rva2VuIiwiemlkIjoidWFhIiwiYXVkIjpbIm9wZW5pZCIsIm9zYi1sb2ctbWV0cmljLXRlc3Quc3lzdGVtLmNmLmhvYi5sb2NhbCIsImNsb3VkX2NvbnRyb2xsZXJfc2VydmljZV9wZXJtaXNzaW9ucyJdfQ.PyCzIMlXg2zdGYPRridAk3XNe3VXIA3DdlMo0zQ0uNLz6lz6U2gTiQ6wbu4UK68VIKj4B-d-T0wriKD3DstgVGhPCDlUZDrlcyTMKcjNeSHTYHf4YDZcaog4L7-m6TnnKrwD51UYDpTqJwKhyhafxGiQ9vdtgoGjlPoNmYlNXKKvglHbR3u3jNHXZFg7JH_ts8bvrfW6jcMx0PzDfUlAFoYDrpMzqPzxnp3qiBV0774ScviuLqk_MwgPnNbRCNVetm-Dnu6cvyaHl1S3APwUnjpp6MisbwNUEV5YveJE0PdQ8er_wvsmZD_DKj5voxEmljc0kbOoXU77ToRO0YVo9g",
    
  } as Environment;
}

export interface Environment {
  realm: string;
  token: string;
}

// overwrite default env with injected vars
export const environment: Environment = Object.assign({}, seedEnv, injectedEnv);